[package]
name = "liescript-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
liescript_lexical = { path = "../liescript-lexical" }
liescript_diagnostic = { path = "../liescript-diagnostic" }
liescript_ast = { path = "../liescript-ast" }
liescript_lexer = { path = "../liescript-lexer" }

[dev-dependencies]
insta = "1.39"
